# Generated by Django 6.1 on 2026-08-08 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_explanation_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processstep',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='system_explanation_services.process'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='system_explanation_services.project'),
        ),
        migrations.AddField(
            model_name='stepcontrol',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='system_explanation_services.processstep'),
        ),
        migrations.AddField(
            model_name='steprisk',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='system_explanation_services.processstep'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['process', 'is_deleted'], name='system_expl_process_ce4cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'is_deleted'], name='system_expl_owner_i_bafc87_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='system_expl_status_f91377_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['project', 'is_deleted'], name='system_expl_project_a3bbf6_idx'),
        ),
    ]
