# Generated by Django 6.1 on 2026-08-08 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_explanation_services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('section', models.CharField(choices=[('explanation', 'Explanation'), ('risk', 'Risk'), ('control', 'Control')], max_length=20)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Required for image/file kinds', null=True, upload_to='step_media/%Y/%m/')),
                ('url', models.URLField(blank=True, default='', help_text='Required for link kind; optional external URL for others')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'step media',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Null = root project. Set to create a sub-project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_projects', to='system_explanation_services.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['parent', 'is_deleted'], name='system_expl_parent__f3f83b_idx'),
        ),
        migrations.AddField(
            model_name='stepmedia',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='system_explanation_services.stepcontrol'),
        ),
        migrations.AddField(
            model_name='stepmedia',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='system_explanation_services.steprisk'),
        ),
        migrations.AddField(
            model_name='stepmedia',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='system_explanation_services.processstep'),
        ),
        migrations.AddIndex(
            model_name='stepmedia',
            index=models.Index(fields=['step', 'section', 'is_deleted'], name='system_expl_step_id_211514_idx'),
        ),
    ]
