# Generated by Django 6.1 on 2026-08-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_explanation_services', '0003_stepmedia_project_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', help_text='Optional text shown on the arrow, e.g. «تایید شد»', max_length=255)),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='system_explanation_services.processstep')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='system_explanation_services.process')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='system_explanation_services.processstep')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['process', 'is_deleted'], name='system_expl_process_7d03c5_idx')],
            },
        ),
    ]
