# Generated by Django 5.2.4 on 2026-08-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_explanation_services', '0005_projectmember'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='system_expl_user_id_915048_idx',
            old_name='system_expl_user_id_6e2a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='system_expl_project_098f8f_idx',
            old_name='system_expl_project_8c1f4e_idx',
        ),
    ]
