# Generated by Django 5.2.4 on 2026-10-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=32)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(default=list, help_text='Subset of email, telegram, whatsapp, sms.')),
                ('mode', models.CharField(choices=[('before', 'Days before the due date, at a time'), ('at', 'At an exact date and time')], default='before', max_length=10)),
                ('offset_days', models.PositiveSmallIntegerField(default=1)),
                ('at_time', models.TimeField(blank=True, help_text='Local time of day for `before` mode.', null=True)),
                ('fixed_at', models.DateTimeField(blank=True, help_text='Exact moment for `at` mode.', null=True)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(default=list, help_text='Subset of email, telegram, whatsapp, sms.')),
                ('mode', models.CharField(choices=[('before', 'Days before the due date, at a time'), ('at', 'At an exact date and time')], default='before', max_length=10)),
                ('offset_days', models.PositiveSmallIntegerField(default=1)),
                ('at_time', models.TimeField(blank=True, help_text='Local time of day for `before` mode.', null=True)),
                ('fixed_at', models.DateTimeField(blank=True, help_text='Exact moment for `at` mode.', null=True)),
                ('target_type', models.CharField(help_text='Registered key, e.g. daybook.plan.', max_length=40)),
                ('target_id', models.PositiveBigIntegerField()),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Per-channel outcome.')),
                ('message', models.TextField(blank=True, default='', help_text='Text that was sent.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='reminder_services.remindergroup')),
            ],
            options={
                'ordering': ['send_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='remindergroup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='reminder_group_unique_name'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'send_at'], name='reminder_due'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['target_type', 'target_id'], name='reminder_target'),
        ),
    ]
