# Generated by Django 5.2.4 on 2026-10-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('price_rial', models.PositiveBigIntegerField(help_text='Snapshot of the price at checkout, in Rial.')),
                ('days', models.PositiveSmallIntegerField(help_text='Length of access this purchase grants.')),
                ('reference', models.CharField(help_text='Shown to the user and on the payment.', max_length=16, unique=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, default='', help_text='Bank / gateway tracking code entered on activation.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status', 'ends_at'], name='sub_user_status_end')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='sub_one_pending_per_user')],
            },
        ),
    ]
